#!/bin/bash

layout_python() {
    VDIR="$1"
    if [[ ! -d  "$VDIR" ]]; then
        python -m venv "$VDIR"
    fi
    source "$VDIR"/bin/activate
    pip install pyflakes
}

export_function() {
  local name="$1"
  local alias_dir="$PWD"/.direnv/aliases
  mkdir -p "$alias_dir"
  PATH_add "$alias_dir"
  local target="$alias_dir/$name"
  if declare -f "$name" >/dev/null; then
    echo "#!/usr/bin/env bash" > "$target"
    declare -f "$name" >> "$target" 2>/dev/null
    # Notice that we add shell variables to the function trigger.
    echo "$name \$*" >> "$target"
    chmod +x "$target"
  fi
}
